version: '3.6'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./pipe:/var/log/mysql/
    restart: always
    command: mysqld --general_log=1 --log_output='FILE' --general-log-file=/var/log/mysql/general.log
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - elk
      
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    # volumes:
      # - ./wordpress/data:/var/www/html/wp-content
    networks:
      - elk
      
  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    depends_on:
      - db
  
  kibana:
    image: kibana:7.14.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.1
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    user: root
    volumes:
      - "./pipe:/var/log/mysql"
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml"
    networks:
      - elk
    depends_on:
      - db
      - elasticsearch
      

networks:
  elk:
    driver: bridge